cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'grc'
brew 'jq'
brew 'libgit2'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'spaceman-diff'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
